--------------------------------------------------------------------------------
-- The Lambek Calculus in Agda
--
-- This file was generated from:
--   src/Logic/LG/ResMon/Origin/El.agda
--------------------------------------------------------------------------------


open import Function                              using (id; flip; _∘_)
open import Relation.Binary.PropositionalEquality using (_≡_; refl; sym; subst)


module Logic.NLP.ResMon.Origin.El {ℓ} (Atom : Set ℓ) where


  open import Logic.Polarity
  open import Logic.NLP.Type                               Atom as T
  open import Logic.NLP.Type.Context.Polarised             Atom as TC
  open import Logic.NLP.ResMon.Sequent                   Atom
  open import Logic.NLP.ResMon.Sequent.Context.Polarised Atom as JC
  open import Logic.NLP.ResMon.Base                        Atom as NLPB


  data Origin {B} ( J : Contextʲ + ) (f : NLP J [ el B ]ʲ) : Set ℓ where
       origin : (f′ : ∀ {G} → NLP G ⊢ el B → NLP J [ G ]ʲ)
              → (pr : f ≡ f′ ax)
              → Origin J f


  mutual
    view : ∀ {B} ( J : Contextʲ + ) (f : NLP J [ el B ]ʲ) → Origin J f
    view ([]   <⊢ ._)  ax = origin (λ {G} z → z) refl
    view ([]   <⊢ ._) (r◇□ x) = {!!}
    view ([]   <⊢ ._) (r⊗⇒ x) = {!!}
    view ([]   <⊢ ._) (r⊗⇐ x) = {!!}
    view (◇> A <⊢ ._) (m◇  x) = {!!}
    view (◇> A <⊢  _) (r□◇ x) = {!!}
    view (◇> A <⊢ ._) (r◇□ x) = {!!}
    view (◇> A <⊢ ._) (r⊗⇒ x) = {!!}
    view (◇> A <⊢ ._) (r⊗⇐ x) = {!!}
    view (el x ⊗> [] <⊢ ._) (r◇□ x₁) = {!!}
    view (el x ⊗> [] <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (el x ⊗> [] <⊢ C) (r⇒⊗ x₁) = {!!}
    view (el x ⊗> [] <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (el x ⊗> [] <⊢ C) (r⇐⊗ x₁) = {!!}
    view (el x ⊗> [] <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (el x ⊗> ◇> B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view (el x ⊗> ◇> B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (el x ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view (el x ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (el x ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view (el x ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (el x ⊗> x₁ ⊗> [] <⊢ ._) (r◇□ x₂) = {!!}
    view (el x ⊗> x₁ ⊗> [] <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> [] <⊢ C) (r⇒⊗ x₂) = {!!}
    view (el x ⊗> x₁ ⊗> [] <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (el x ⊗> x₁ ⊗> [] <⊢ C) (r⇐⊗ x₂) = {!!}
    view (el x ⊗> x₁ ⊗> [] <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (el x ⊗> ._ ⊗> [] <⊢ C) (p2′ x₁) = {!!}
    view (el x ⊗> x₁ ⊗> ◇> B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (el x ⊗> x₁ ⊗> ◇> B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (el x ⊗> x₁ ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (el x ⊗> x₁ ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (el x ⊗> x₁ ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (el x ⊗> x₁ ⊗> ◇> B₁ <⊢ C) (p1 x₂) = {!!}
    view (el x ⊗> ._ ⊗> ◇> B₁ <⊢ C) (p2′ x₁) = {!!}
    view (el x ⊗> x₁ ⊗> x₂ ⊗> B₁ <⊢ ._) (r◇□ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> x₂ ⊗> B₁ <⊢ ._) (m⊗ x₃ x₄) = {!!}
    view (el x ⊗> x₁ ⊗> x₂ ⊗> B₁ <⊢ C) (r⇒⊗ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> x₂ ⊗> B₁ <⊢ ._) (r⊗⇒ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> x₂ ⊗> B₁ <⊢ C) (r⇐⊗ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> x₂ ⊗> B₁ <⊢ ._) (r⊗⇐ x₃) = {!!}
    view (el x ⊗> ._ ⊗> x₂ ⊗> B₁ <⊢ C) (p2′ x₁) = {!!}
    view (el x ⊗> x₁ ⊗> B₁ <⊗ x₂ <⊢ ._) (r◇□ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> B₁ <⊗ x₂ <⊢ ._) (m⊗ x₃ x₄) = {!!}
    view (el x ⊗> x₁ ⊗> B₁ <⊗ x₂ <⊢ C) (r⇒⊗ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> B₁ <⊗ x₂ <⊢ ._) (r⊗⇒ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> B₁ <⊗ x₂ <⊢ C) (r⇐⊗ x₃) = {!!}
    view (el x ⊗> x₁ ⊗> B₁ <⊗ x₂ <⊢ ._) (r⊗⇐ x₃) = {!!}
    view (el x ⊗> ._ ⊗> B₁ <⊗ x₂ <⊢ C) (p2′ x₁) = {!!}
    view (el x ⊗> [] <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (el x ⊗> [] <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (el x ⊗> [] <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (el x ⊗> [] <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (el x ⊗> [] <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (el x ⊗> [] <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (el x ⊗> [] <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view (el x ⊗> ◇> B₁ <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (el x ⊗> ◇> B₁ <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (el x ⊗> ◇> B₁ <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (el x ⊗> ◇> B₁ <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (el x ⊗> ◇> B₁ <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (el x ⊗> ◇> B₁ <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (el x ⊗> ◇> B₁ <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view (el x ⊗> ◇> B₁ <⊗ x₁ <⊢ C) (p2′ x₂) = {!!}
    view (el x ⊗> (x₁ ⊗> B₁) <⊗ x₂ <⊢ ._) (r◇□ x₃) = {!!}
    view (el x ⊗> (x₁ ⊗> B₁) <⊗ x₂ <⊢ ._) (m⊗ x₃ x₄) = {!!}
    view (el x ⊗> (x₁ ⊗> B₁) <⊗ x₂ <⊢ C) (r⇒⊗ x₃) = {!!}
    view (el x ⊗> (x₁ ⊗> B₁) <⊗ x₂ <⊢ ._) (r⊗⇒ x₃) = {!!}
    view (el x ⊗> (x₁ ⊗> B₁) <⊗ x₂ <⊢ C) (r⇐⊗ x₃) = {!!}
    view (el x ⊗> (x₁ ⊗> B₁) <⊗ x₂ <⊢ ._) (r⊗⇐ x₃) = {!!}
    view (el x ⊗> (x₁ ⊗> B₁) <⊗ ._ <⊢ C) (p1 x₂) = {!!}
    view (el x ⊗> (B₁ <⊗ x₁) <⊗ x₂ <⊢ ._) (r◇□ x₃) = {!!}
    view (el x ⊗> (B₁ <⊗ x₁) <⊗ x₂ <⊢ ._) (m⊗ x₃ x₄) = {!!}
    view (el x ⊗> (B₁ <⊗ x₁) <⊗ x₂ <⊢ C) (r⇒⊗ x₃) = {!!}
    view (el x ⊗> (B₁ <⊗ x₁) <⊗ x₂ <⊢ ._) (r⊗⇒ x₃) = {!!}
    view (el x ⊗> (B₁ <⊗ x₁) <⊗ x₂ <⊢ C) (r⇐⊗ x₃) = {!!}
    view (el x ⊗> (B₁ <⊗ x₁) <⊗ x₂ <⊢ ._) (r⊗⇐ x₃) = {!!}
    view (el x ⊗> (B₁ <⊗ x₁) <⊗ ._ <⊢ C) (p1 x₂) = {!!}
    view (□ A ⊗> [] <⊢ ._) (r◇□ x) = {!!}
    view (□ A ⊗> [] <⊢ ._) (m⊗ x x₁) = {!!}
    view (□ A ⊗> [] <⊢ C) (r⇒⊗ x) = {!!}
    view (□ A ⊗> [] <⊢ ._) (r⊗⇒ x) = {!!}
    view (□ A ⊗> [] <⊢ C) (r⇐⊗ x) = {!!}
    view (□ A ⊗> [] <⊢ ._) (r⊗⇐ x) = {!!}
    view (□ A ⊗> ◇> B₁ <⊢ ._) (r◇□ x) = {!!}
    view (□ A ⊗> ◇> B₁ <⊢ ._) (m⊗ x x₁) = {!!}
    view (□ A ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x) = {!!}
    view (□ A ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x) = {!!}
    view (□ A ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x) = {!!}
    view (□ A ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x) = {!!}
    view (□ A ⊗> x ⊗> [] <⊢ ._) (r◇□ x₁) = {!!}
    view (□ A ⊗> x ⊗> [] <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (□ A ⊗> x ⊗> [] <⊢ C) (r⇒⊗ x₁) = {!!}
    view (□ A ⊗> x ⊗> [] <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (□ A ⊗> x ⊗> [] <⊢ C) (r⇐⊗ x₁) = {!!}
    view (□ A ⊗> x ⊗> [] <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (□ A ⊗> ._ ⊗> [] <⊢ C) (p2′ x) = {!!}
    view (□ A ⊗> x ⊗> ◇> B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view (□ A ⊗> x ⊗> ◇> B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (□ A ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view (□ A ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (□ A ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view (□ A ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (□ A ⊗> x ⊗> ◇> B₁ <⊢ C) (p1 x₁) = {!!}
    view (□ A ⊗> ._ ⊗> ◇> B₁ <⊢ C) (p2′ x) = {!!}
    view (□ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (□ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (□ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (□ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (□ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (□ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (□ A ⊗> ._ ⊗> x₁ ⊗> B₁ <⊢ C) (p2′ x) = {!!}
    view (□ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (□ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (□ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (□ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (□ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (□ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (□ A ⊗> ._ ⊗> B₁ <⊗ x₁ <⊢ C) (p2′ x) = {!!}
    view (□ A ⊗> [] <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view (□ A ⊗> [] <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (□ A ⊗> [] <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view (□ A ⊗> [] <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (□ A ⊗> [] <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view (□ A ⊗> [] <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (□ A ⊗> [] <⊗ ._ <⊢ C) (p1 x) = {!!}
    view (□ A ⊗> ◇> B₁ <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view (□ A ⊗> ◇> B₁ <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (□ A ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view (□ A ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (□ A ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view (□ A ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (□ A ⊗> ◇> B₁ <⊗ ._ <⊢ C) (p1 x) = {!!}
    view (□ A ⊗> ◇> B₁ <⊗ x <⊢ C) (p2′ x₁) = {!!}
    view (□ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (□ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (□ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (□ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (□ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (□ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (□ A ⊗> (x ⊗> B₁) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view (□ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (□ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (□ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (□ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (□ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (□ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (□ A ⊗> (B₁ <⊗ x) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view (◇ A ⊗> [] <⊢ ._) (r◇□ x) = {!!}
    view (◇ A ⊗> [] <⊢ ._) (m⊗ x x₁) = {!!}
    view (◇ A ⊗> [] <⊢ C) (r⇒⊗ x) = {!!}
    view (◇ A ⊗> [] <⊢ ._) (r⊗⇒ x) = {!!}
    view (◇ A ⊗> [] <⊢ C) (r⇐⊗ x) = {!!}
    view (◇ A ⊗> [] <⊢ ._) (r⊗⇐ x) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊢ ._) (r◇□ x) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊢ ._) (m⊗ x x₁) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x) = {!!}
    view (◇ A ⊗> x ⊗> [] <⊢ ._) (r◇□ x₁) = {!!}
    view (◇ A ⊗> x ⊗> [] <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (◇ A ⊗> x ⊗> [] <⊢ C) (r⇒⊗ x₁) = {!!}
    view (◇ A ⊗> x ⊗> [] <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (◇ A ⊗> x ⊗> [] <⊢ C) (r⇐⊗ x₁) = {!!}
    view (◇ A ⊗> x ⊗> [] <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (◇ A ⊗> ._ ⊗> [] <⊢ C) (p2′ x) = {!!}
    view (◇ A ⊗> x ⊗> ◇> B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view (◇ A ⊗> x ⊗> ◇> B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (◇ A ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view (◇ A ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (◇ A ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view (◇ A ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (◇ A ⊗> x ⊗> ◇> B₁ <⊢ C) (p1 x₁) = {!!}
    view (◇ A ⊗> ._ ⊗> ◇> B₁ <⊢ C) (p2′ x) = {!!}
    view (◇ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (◇ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (◇ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (◇ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (◇ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (◇ A ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (◇ A ⊗> ._ ⊗> x₁ ⊗> B₁ <⊢ C) (p2′ x) = {!!}
    view (◇ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (◇ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (◇ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (◇ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (◇ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (◇ A ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (◇ A ⊗> ._ ⊗> B₁ <⊗ x₁ <⊢ C) (p2′ x) = {!!}
    view (◇ A ⊗> [] <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view (◇ A ⊗> [] <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (◇ A ⊗> [] <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view (◇ A ⊗> [] <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (◇ A ⊗> [] <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view (◇ A ⊗> [] <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (◇ A ⊗> [] <⊗ ._ <⊢ C) (p1 x) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊗ ._ <⊢ C) (p1 x) = {!!}
    view (◇ A ⊗> ◇> B₁ <⊗ x <⊢ C) (p2′ x₁) = {!!}
    view (◇ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (◇ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (◇ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (◇ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (◇ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (◇ A ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (◇ A ⊗> (x ⊗> B₁) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view (◇ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (◇ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (◇ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (◇ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (◇ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (◇ A ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (◇ A ⊗> (B₁ <⊗ x) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊢ ._) (r◇□ x) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊢ ._) (m⊗ x x₁) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊢ C) (r⇒⊗ x) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊢ ._) (r⊗⇒ x) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊢ C) (r⇐⊗ x) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊢ ._) (r⊗⇐ x) = {!!}
    view ((A ⊗ ._) ⊗> [] <⊢ C) (p2 x) = {!!}
    view ((._ ⊗ A₁) ⊗> [] <⊢ C) (p1′ x) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊢ ._) (r◇□ x) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊢ ._) (m⊗ x x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x) = {!!}
    view ((A ⊗ ._) ⊗> ◇> B₁ <⊢ C) (p2 x) = {!!}
    view ((._ ⊗ A₁) ⊗> ◇> B₁ <⊢ C) (p1′ x) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> [] <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> [] <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> [] <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> [] <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> [] <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> [] <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⊗ ._) ⊗> x ⊗> [] <⊢ C) (p2 x₁) = {!!}
    view ((._ ⊗ A₁) ⊗> x ⊗> [] <⊢ C) (p1′ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ._ ⊗> [] <⊢ C) (p2′ x) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (p1 x₁) = {!!}
    view ((A ⊗ ._) ⊗> x ⊗> ◇> B₁ <⊢ C) (p2 x₁) = {!!}
    view ((._ ⊗ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (p1′ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ._ ⊗> ◇> B₁ <⊢ C) (p2′ x) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⊗ ._) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (p2 x₂) = {!!}
    view ((._ ⊗ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (p1′ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> ._ ⊗> x₁ ⊗> B₁ <⊢ C) (p2′ x) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⊗ ._) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (p2 x₂) = {!!}
    view ((._ ⊗ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (p1′ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> ._ ⊗> B₁ <⊗ x₁ <⊢ C) (p2′ x) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> [] <⊗ ._ <⊢ C) (p1 x) = {!!}
    view ((A ⊗ ._) ⊗> [] <⊗ x <⊢ C) (p2 x₁) = {!!}
    view ((._ ⊗ A₁) ⊗> [] <⊗ x <⊢ C) (p1′ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊗ ._ <⊢ C) (p1 x) = {!!}
    view ((A ⊗ ._) ⊗> ◇> B₁ <⊗ x <⊢ C) (p2 x₁) = {!!}
    view ((._ ⊗ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (p1′ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (p2′ x₁) = {!!}
    view ((A ⊗ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⊗ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (x ⊗> B₁) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ((A ⊗ ._) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (p2 x₂) = {!!}
    view ((._ ⊗ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (p1′ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⊗ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⊗ A₁) ⊗> (B₁ <⊗ x) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ((A ⊗ ._) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (p2 x₂) = {!!}
    view ((._ ⊗ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (p1′ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊢ ._) (r◇□ x) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊢ ._) (m⊗ x x₁) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊢ C) (r⇒⊗ x) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊢ ._) (r⊗⇒ x) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊢ C) (r⇐⊗ x) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊢ ._) (r⊗⇐ x) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊢ ._) (r◇□ x) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊢ ._) (m⊗ x x₁) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> [] <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> [] <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> [] <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> [] <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> [] <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> [] <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> ._ ⊗> [] <⊢ C) (p2′ x) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (p1 x₁) = {!!}
    view ((A ⇒ A₁) ⊗> ._ ⊗> ◇> B₁ <⊢ C) (p2′ x) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> ._ ⊗> x₁ ⊗> B₁ <⊢ C) (p2′ x) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> ._ ⊗> B₁ <⊗ x₁ <⊢ C) (p2′ x) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> [] <⊗ ._ <⊢ C) (p1 x) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊗ ._ <⊢ C) (p1 x) = {!!}
    view ((A ⇒ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (p2′ x₁) = {!!}
    view ((A ⇒ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⇒ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (x ⊗> B₁) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ((A ⇒ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⇒ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⇒ A₁) ⊗> (B₁ <⊗ x) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊢ ._) (r◇□ x) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊢ ._) (m⊗ x x₁) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊢ C) (r⇒⊗ x) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊢ ._) (r⊗⇒ x) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊢ C) (r⇐⊗ x) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊢ ._) (r⊗⇐ x) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊢ ._) (r◇□ x) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊢ ._) (m⊗ x x₁) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> [] <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> [] <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> [] <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> [] <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> [] <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> [] <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> ._ ⊗> [] <⊢ C) (p2′ x) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> ◇> B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> ◇> B₁ <⊢ C) (p1 x₁) = {!!}
    view ((A ⇐ A₁) ⊗> ._ ⊗> ◇> B₁ <⊢ C) (p2′ x) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> x₁ ⊗> B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> ._ ⊗> x₁ ⊗> B₁ <⊢ C) (p2′ x) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> x ⊗> B₁ <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> ._ ⊗> B₁ <⊗ x₁ <⊢ C) (p2′ x) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> [] <⊗ ._ <⊢ C) (p1 x) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (r◇□ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊗ x <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊗ ._ <⊢ C) (p1 x) = {!!}
    view ((A ⇐ A₁) ⊗> ◇> B₁ <⊗ x <⊢ C) (p2′ x₁) = {!!}
    view ((A ⇐ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⇐ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (x ⊗> B₁) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (x ⊗> B₁) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ((A ⇐ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((A ⇐ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (B₁ <⊗ x) <⊗ x₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((A ⇐ A₁) ⊗> (B₁ <⊗ x) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ([] <⊗ B₁ <⊢ ._) (r◇□ x) = {!!}
    view ([] <⊗ B₁ <⊢ ._) (m⊗ x x₁) = {!!}
    view ([] <⊗ B₁ <⊢ C) (r⇒⊗ x) = {!!}
    view ([] <⊗ B₁ <⊢ ._) (r⊗⇒ x) = {!!}
    view ([] <⊗ B₁ <⊢ C) (r⇐⊗ x) = {!!}
    view ([] <⊗ B₁ <⊢ ._) (r⊗⇐ x) = {!!}
    view ([] <⊗ ._ <⊢ C) (p1 x) = {!!}
    view ([] <⊗ ._ <⊢ C) (p2′ x) = {!!}
    view (◇> A <⊗ B₁ <⊢ ._) (r◇□ x) = {!!}
    view (◇> A <⊗ B₁ <⊢ ._) (m⊗ x x₁) = {!!}
    view (◇> A <⊗ B₁ <⊢ C) (r⇒⊗ x) = {!!}
    view (◇> A <⊗ B₁ <⊢ ._) (r⊗⇒ x) = {!!}
    view (◇> A <⊗ B₁ <⊢ C) (r⇐⊗ x) = {!!}
    view (◇> A <⊗ B₁ <⊢ ._) (r⊗⇐ x) = {!!}
    view (◇> A <⊗ ._ <⊢ C) (p1 x) = {!!}
    view (◇> A <⊗ ._ <⊢ C) (p2′ x) = {!!}
    view ((x ⊗> []) <⊗ B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view ((x ⊗> []) <⊗ B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((x ⊗> []) <⊗ B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((x ⊗> []) <⊗ B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((x ⊗> []) <⊗ B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((x ⊗> []) <⊗ B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((x ⊗> []) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ((._ ⊗> []) <⊗ B₁ <⊢ C) (p1′ x) = {!!}
    view ((x ⊗> []) <⊗ ._ <⊢ C) (p2′ x₁) = {!!}
    view ((x ⊗> ◇> A) <⊗ B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view ((x ⊗> ◇> A) <⊗ B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((x ⊗> ◇> A) <⊗ B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((x ⊗> ◇> A) <⊗ B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((x ⊗> ◇> A) <⊗ B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((x ⊗> ◇> A) <⊗ B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((x ⊗> ◇> A) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ((x ⊗> ◇> A) <⊗ B₁ <⊢ C) (p2 x₁) = {!!}
    view ((._ ⊗> ◇> A) <⊗ B₁ <⊢ C) (p1′ x) = {!!}
    view ((x ⊗> ◇> A) <⊗ ._ <⊢ C) (p2′ x₁) = {!!}
    view ((x ⊗> x₁ ⊗> A) <⊗ B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((x ⊗> x₁ ⊗> A) <⊗ B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((x ⊗> x₁ ⊗> A) <⊗ B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((x ⊗> x₁ ⊗> A) <⊗ B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((x ⊗> x₁ ⊗> A) <⊗ B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((x ⊗> x₁ ⊗> A) <⊗ B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((x ⊗> x₁ ⊗> A) <⊗ ._ <⊢ C) (p1 x₂) = {!!}
    view ((._ ⊗> x₁ ⊗> A) <⊗ B₁ <⊢ C) (p1′ x) = {!!}
    view ((x ⊗> x₁ ⊗> A) <⊗ ._ <⊢ C) (p2′ x₂) = {!!}
    view ((x ⊗> A <⊗ x₁) <⊗ B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view ((x ⊗> A <⊗ x₁) <⊗ B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view ((x ⊗> A <⊗ x₁) <⊗ B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view ((x ⊗> A <⊗ x₁) <⊗ B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view ((x ⊗> A <⊗ x₁) <⊗ B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view ((x ⊗> A <⊗ x₁) <⊗ B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view ((x ⊗> A <⊗ x₁) <⊗ ._ <⊢ C) (p1 x₂) = {!!}
    view ((._ ⊗> A <⊗ x₁) <⊗ B₁ <⊢ C) (p1′ x) = {!!}
    view ((x ⊗> A <⊗ x₁) <⊗ ._ <⊢ C) (p2′ x₂) = {!!}
    view (([] <⊗ x) <⊗ B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view (([] <⊗ x) <⊗ B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view (([] <⊗ x) <⊗ B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view (([] <⊗ x) <⊗ B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view (([] <⊗ x) <⊗ B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view (([] <⊗ x) <⊗ B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view (([] <⊗ x) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view (([] <⊗ ._) <⊗ B₁ <⊢ C) (p2 x) = {!!}
    view (([] <⊗ x) <⊗ ._ <⊢ C) (p2′ x₁) = {!!}
    view ((◇> A <⊗ x) <⊗ B₁ <⊢ ._) (r◇□ x₁) = {!!}
    view ((◇> A <⊗ x) <⊗ B₁ <⊢ ._) (m⊗ x₁ x₂) = {!!}
    view ((◇> A <⊗ x) <⊗ B₁ <⊢ C) (r⇒⊗ x₁) = {!!}
    view ((◇> A <⊗ x) <⊗ B₁ <⊢ ._) (r⊗⇒ x₁) = {!!}
    view ((◇> A <⊗ x) <⊗ B₁ <⊢ C) (r⇐⊗ x₁) = {!!}
    view ((◇> A <⊗ x) <⊗ B₁ <⊢ ._) (r⊗⇐ x₁) = {!!}
    view ((◇> A <⊗ x) <⊗ ._ <⊢ C) (p1 x₁) = {!!}
    view ((◇> A <⊗ ._) <⊗ B₁ <⊢ C) (p2 x) = {!!}
    view ((◇> A <⊗ x) <⊗ B₁ <⊢ C) (p1′ x₁) = {!!}
    view ((◇> A <⊗ x) <⊗ ._ <⊢ C) (p2′ x₁) = {!!}
    view (((x ⊗> A) <⊗ x₁) <⊗ B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (((x ⊗> A) <⊗ x₁) <⊗ B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (((x ⊗> A) <⊗ x₁) <⊗ B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (((x ⊗> A) <⊗ x₁) <⊗ B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (((x ⊗> A) <⊗ x₁) <⊗ B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (((x ⊗> A) <⊗ x₁) <⊗ B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (((x ⊗> A) <⊗ x₁) <⊗ ._ <⊢ C) (p1 x₂) = {!!}
    view (((x ⊗> A) <⊗ ._) <⊗ B₁ <⊢ C) (p2 x₁) = {!!}
    view (((x ⊗> A) <⊗ x₁) <⊗ ._ <⊢ C) (p2′ x₂) = {!!}
    view (((A <⊗ x) <⊗ x₁) <⊗ B₁ <⊢ ._) (r◇□ x₂) = {!!}
    view (((A <⊗ x) <⊗ x₁) <⊗ B₁ <⊢ ._) (m⊗ x₂ x₃) = {!!}
    view (((A <⊗ x) <⊗ x₁) <⊗ B₁ <⊢ C) (r⇒⊗ x₂) = {!!}
    view (((A <⊗ x) <⊗ x₁) <⊗ B₁ <⊢ ._) (r⊗⇒ x₂) = {!!}
    view (((A <⊗ x) <⊗ x₁) <⊗ B₁ <⊢ C) (r⇐⊗ x₂) = {!!}
    view (((A <⊗ x) <⊗ x₁) <⊗ B₁ <⊢ ._) (r⊗⇐ x₂) = {!!}
    view (((A <⊗ x) <⊗ x₁) <⊗ ._ <⊢ C) (p1 x₂) = {!!}
    view (((A <⊗ x) <⊗ ._) <⊗ B₁ <⊢ C) (p2 x₁) = {!!}
    view (((A <⊗ x) <⊗ x₁) <⊗ ._ <⊢ C) (p2′ x₂) = {!!}
    view (._ ⊢> □> B₁) (m□ x) = {!!}
    view (._ ⊢> □> B₁) (r□◇ x) = {!!}
    view (A ⊢> □> B₁) (r◇□ x) = {!!}
    view (._ ⊢> □> B₁) (r⇒⊗ x) = {!!}
    view (._ ⊢> □> B₁) (r⇐⊗ x) = {!!}
    view (._ ⊢> □> B₁) (p1 x) = {!!}
    view (._ ⊢> □> B₁) (p2 x) = {!!}
    view (._ ⊢> □> B₁) (p1′ x) = {!!}
    view (._ ⊢> □> B₁) (p2′ x) = {!!}
    view (._ ⊢> x ⇒> B₁) (r□◇ x₁) = {!!}
    view (._ ⊢> x ⇒> B₁) (m⇒ x₁ x₂) = {!!}
    view (._ ⊢> x ⇒> B₁) (r⇒⊗ x₁) = {!!}
    view (A ⊢> x ⇒> B₁) (r⊗⇒ x₁) = {!!}
    view (._ ⊢> x ⇒> B₁) (r⇐⊗ x₁) = {!!}
    view (._ ⊢> x ⇒> B₁) (p1 x₁) = {!!}
    view (._ ⊢> x ⇒> B₁) (p2 x₁) = {!!}
    view (._ ⊢> x ⇒> B₁) (p1′ x₁) = {!!}
    view (._ ⊢> x ⇒> B₁) (p2′ x₁) = {!!}
    view (._ ⊢> x ⇐> B₁) (r□◇ x₁) = {!!}
    view (._ ⊢> x ⇐> B₁) (m⇐ x₁ x₂) = {!!}
    view (._ ⊢> x ⇐> B₁) (r⇒⊗ x₁) = {!!}
    view (._ ⊢> x ⇐> B₁) (r⇐⊗ x₁) = {!!}
    view (A ⊢> x ⇐> B₁) (r⊗⇐ x₁) = {!!}
    view (._ ⊢> x ⇐> B₁) (p1 x₁) = {!!}
    view (._ ⊢> x ⇐> B₁) (p2 x₁) = {!!}
    view (._ ⊢> x ⇐> B₁) (p1′ x₁) = {!!}
    view (._ ⊢> x ⇐> B₁) (p2′ x₁) = {!!}
    view (._ ⊢> B₁ <⇒ x) (r□◇ x₁) = {!!}
    view (._ ⊢> B₁ <⇒ x) (m⇒ x₁ x₂) = {!!}
    view (._ ⊢> B₁ <⇒ x) (r⇒⊗ x₁) = {!!}
    view (A ⊢> B₁ <⇒ x) (r⊗⇒ x₁) = {!!}
    view (._ ⊢> B₁ <⇒ x) (r⇐⊗ x₁) = {!!}
    view (._ ⊢> B₁ <⇒ x) (p1 x₁) = {!!}
    view (._ ⊢> B₁ <⇒ x) (p2 x₁) = {!!}
    view (._ ⊢> B₁ <⇒ x) (p1′ x₁) = {!!}
    view (._ ⊢> B₁ <⇒ x) (p2′ x₁) = {!!}
    view (._ ⊢> B₁ <⇐ x) (r□◇ x₁) = {!!}
    view (._ ⊢> B₁ <⇐ x) (m⇐ x₁ x₂) = {!!}
    view (._ ⊢> B₁ <⇐ x) (r⇒⊗ x₁) = {!!}
    view (._ ⊢> B₁ <⇐ x) (r⇐⊗ x₁) = {!!}
    view (A ⊢> B₁ <⇐ x) (r⊗⇐ x₁) = {!!}
    view (._ ⊢> B₁ <⇐ x) (p1 x₁) = {!!}
    view (._ ⊢> B₁ <⇐ x) (p2 x₁) = {!!}
    view (._ ⊢> B₁ <⇐ x) (p1′ x₁) = {!!}
    view (._ ⊢> B₁ <⇐ x) (p2′ x₁) = {!!}

    private
      go : ∀ {B}
         → ( I : Contextʲ + ) (f : NLP I [ el B ]ʲ)
         → { J : Contextʲ + } (g : ∀ {G} → NLP I [ G ]ʲ → NLP J [ G ]ʲ)
         → Origin J (g f)
      go I f {J} g with view I f
      ... | origin f′ pr rewrite pr = origin (g ∘ f′) refl
